apiVersion: platform.example.com/v1
kind: ServiceInfrastructure

metadata:
  name: test
  owner: group:default/guests

spec:
  postgres:
    enabled: true
    engine: postgres
    engine_version: "16"
    instance_class: db.t4g.micro
    allocated_storage: 20
    multi_az: false
    backup_retention_period: 7
    deletion_protection: false
    publicly_accessible: false
