apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: standard-service
  title: Create a new Microservice
spec:
  parameters:
    - title: Basic Info
      properties:
        component_id:
          title: Service Name
          type: string
        owner:
          title: Owner
          type: string
          ui:field: OwnerPicker
    - title: Infrastructure Options
      properties:
        include_rds:
          title: Do you need a Database?
          type: boolean
          default: false
steps:
    - id: template
      name: Generating the Files
      action: fetch:template
      input:
        url: ./skeleton # A folder containing your Dockerfile, k8s manifests, and tf files
        values:
          component_id: ${{ parameters.component_id }}
          include_rds: ${{ parameters.include_rds }}

    - id: publish
      name: Publishing to GitHub
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: 'New service managed by IDP'
        repoUrl: 'github.com?owner=your-org&repo=${{ parameters.component_id }}'