apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{ values.name }}
  labels:
    app.kubernetes.io/name: ${{ values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ${{ values.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ${{ values.name }}
    spec:
      containers:
        - name: ${{ values.name }}
          image: ghcr.io/YOUR_ORG/${{ values.name }}:latest
          ports:
            - containerPort: 8080