name: Terraform Apply

on:
  push:
    branches:
      - main
    paths:
      - "backstage/infra_request/services/**"
      - "terraform/**"

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        run: terraform init

      - name: Terraform apply
        run: terraform apply -auto-approve